Add safeguard against stuck connection.
marvinroger/async-mqtt-client pull request #250
Opened 2021-07-15 11:36 UTC by rousveiga

Fixes https://github.com/marvinroger/async-mqtt-client/issues/248, fix by https://github.com/mcspr/async-mqtt-client/commit/c1fcfd1.

2021-07-16 05:27 UTC, bertmelis commented
Could you try the following:
Set the timeout to 10sec in the _onConnect ad reset in _clear and _onData (maybe only when CONNACK is received)

The way you did it now is on every outgoing message.

2021-07-16 06:03 UTC, bertmelis requested changes

2021-07-16 06:03 UTC, bertmelis commented on src/AsyncMqttClient.cpp
> +  _client.setRxTimeout(10);
Better to move this line to 'connect'. We don't want to set the timeout on every outgoing packet.

2021-07-16 08:28 UTC, bertmelis commented on src/AsyncMqttClient.cpp
> +  _client.setRxTimeout(10);
Oh, and what about using the keepalive value as timeout (seconds!) instead of hardcode to 10 seconds?

2021-07-19 07:47 UTC, rousveiga commented
Like this?

2021-07-19 12:51 UTC, bertmelis commented
> Like this?

Yes, I assume it is still working?

2021-07-19 12:51 UTC, bertmelis approved these changes

2021-07-19 13:27 UTC, vuthuy6586 approved these changes

2021-07-19 15:05 UTC, merged

2021-07-23 08:53 UTC, rousveiga commented
> Yes, I assume it is still working?

Sorry for the delay, yes it works fine!